### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by dawnE64** [jpm96744/TSP_Fancy#6]
```
2022.2.1/plugins/python/helpers/pydev/pydevd.py" --multiprocess --qt-support=auto --client 127.0.0.1 --port 52507 --file C:/Users/johnm/PycharmProjects/TSP_Fancy/Proj5GUI.py 
Traceback (most recent call last):
  File "C:/Users/johnm/PycharmProjects/TSP_Fancy/Proj5GUI.py", line 287, in solveClicked
    results = eval(solve_func)(time_allowance=max_time )
  File "C:\Users\johnm\PycharmProjects\TSP_Fancy\TSPSolver.py", line 189, in fancy
    distance = distance + cities[antPath[i][0]].costTo(cities[antPath[i][1]])
IndexError: list index out of range
```

**Comment by dawnE64** [comment]
This happens if I just run with the settings you set up in Proj5GUI.py

**Comment by dawnE64** [comment]
Fixed by removing -1 from the c range
